### ISSUE TITLE
Unable to authenticate users on swagger doc through the Authorize "OAuth2PasswordBearer" form

### ISSUE THREAD

**Issue by germainlefebvre4** [code-specialist/fastapi-keycloak#11]
Unable to connect with user (here `test@test.fr`) using the "Authorize" button and "OAuth2PasswordBearer" form.
![2022-01-06 08_48_55-FastAPI - Swagger UI](https://user-images.githubusercontent.com/7525033/148348526-594fbe61-c254-4fe1-b971-e415021348a2.png)

A CORS error is achieved on non-https website.
![2022-01-06 08_46_49-FastAPI - Swagger UI](https://user-images.githubusercontent.com/7525033/148348540-f48248ab-9318-4489-9c76-e3dcb24ba7bc.png)

I suggest adding the parameter on your documentation to allow testing the whole process on dev platform (that i the point of playing the quickstart guide).

> Client> test-client : Fil lthe `WebOrigins` attribute to `*`.

![2022-01-06 08_55_41-Keycloak Admin Console](https://user-images.githubusercontent.com/7525033/148348753-f62f71d9-111b-4bb3-b43f-0ce7361a503a.png)

**Comment by yannicschroeer** [comment]
Thanks for pointing this out! We will add your suggestion.

**Comment by code-specialist** [comment]
Has been added.
