### ISSUE TITLE
manifest for jboss/keycloak:16.0.1 not found

### ISSUE THREAD

**Issue by julj** [code-specialist/fastapi-keycloak#25]
Hi,

it seems that the keycloak image tag used in the docker-compose file example in doc/getting_started does not exist:
`ERROR: manifest for jboss/keycloak:16.0.1 not found`
The existing tags are shown [here](https://hub.docker.com/r/jboss/keycloak/tags) (I used 16.1.1).

**Comment by yannicschroeer** [comment]
Hi @julj, thanks for reaching out! How did you encounter the error with the manifest? I think someone spotted and fixed this already like 2 months ago in #12. Did we miss something?

**Comment by yannicschroeer** [comment]
Oh yeah, it's still wrong in the quickstart. Thank you!
