### ISSUE TITLE
Upload Example file for fastapi scopes declaration with keycloak support

### ISSUE THREAD

**Issue by Udayaprasad** [code-specialist/fastapi-keycloak#41]
@yannicschroeer ,

Any timeline for uploading the FastAPI scopes check example using this library?

Also, I would like to know, if there is an example to configure SSO for multiple microservices and MFA

Thanks,
Uday

**Comment by yannicschroeer** [comment]
Hello @Udayaprasad, 

Regarding the scopes, we have another library [fastapi-auth-middleware](https://fastapi-auth-middleware.code-specialist.com/examples/simple_with_scopes/) that supports scopes usage in FastAPI and works fine with this package.

Currently, we do not have any examples/functionality regarding SSO or MFA and do not have the capacity to drive the development of the library on our own. Pull requests are welcome here :)

**Comment by Udayaprasad** [comment]
I have gone through that another library, but I haven't found an example with keycloak and FastAPI scopes. This example is important for us to proceed with Authentication and Authorization integration with keycloak.
@yannicschroeer

**Comment by yannicschroeer** [comment]
We offer this library for others to use and expand and are accommodating support for it. Unfortunately we cannot offer consultation on unrelated matters. If you have specific questions to our library, feel free to reopen this issue.
