### ISSUE TITLE
Extra fields in OIDCUser.

### ISSUE THREAD

**Issue by twistfire92** [code-specialist/fastapi-keycloak#49]
JWT may contain additional data, but there is no field for this data in the OIDCUser model

**Comment by twistfire92** [comment]
resolve with pull request #50

**Comment by chirdeeptomar** [comment]
#50 Has a bug, please review my comment

**Comment by yannicschroeer** [comment]
> #50 Has a bug, please review my comment 

Which comment are you referring to?

**Comment by chirdeeptomar** [comment]
user.extra_fields[field] = decoded_token.get(field, None)
TypeError: 'NoneType' object does not support item assignment.

Initialize at line 275, user.extra_fields = {}
