### ISSUE TITLE
how to assign client roles to a user

### ISSUE THREAD

**Issue by Speccy-Rom** [code-specialist/fastapi-keycloak#85]
I want to assign a keycloak user who already exists a client role, but according to the existing methods in your library I can only assign roles in realm (Realm Roles)
How can I assign a client role to a user with your library?
[https://postimg.cc/G48RwMQ5](url)
Thanks

**Comment by yannicschroeer** [comment]
Hello, that is currently not supported. We're open to pull requests though ✌️

**Comment by yannicschroeer** [comment]
I have no idea what the current Keycloak API offers. Sorry.
